{"EventId":441733974,"LogLevel":"Information","Category":"CustomCategory_TestSignalWithCustomTransport","Message":"Handling signal on test-transport publisher (Signal ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling signal on test-transport publisher (Signal ID: test-message-id, Trace ID: test-trace-id)","TransportTypeName":"test-transport","TransportRole":"publisher","SignalId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling signal on {TransportTypeName:l} {TransportRole:l} (Signal ID: {SignalId:l}, Trace ID: {TraceId:l})"}}
{"EventId":441733974,"LogLevel":"Information","Category":"CustomCategory_TestSignalWithCustomTransport","Message":"Handling signal on test-transport receiver (Signal ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling signal on test-transport receiver (Signal ID: test-message-id, Trace ID: test-trace-id)","TransportTypeName":"test-transport","TransportRole":"receiver","SignalId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling signal on {TransportTypeName:l} {TransportRole:l} (Signal ID: {SignalId:l}, Trace ID: {TraceId:l})"}}
{"EventId":712209902,"LogLevel":"Error","Category":"CustomCategory_TestSignalWithCustomTransport","Message":"An exception occurred while handling signal on test-transport receiver after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomTransportHandler.Handle(TestSignalWithCustomTransport signal, CancellationToken cancellationToken) in {ProjectDirectory}Signalling/LoggingMiddlewareTestSignals.cs:line FIXED\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware\u00601.Execute(SignalMiddlewareContext\u00601 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Signalling/LoggingSignalMiddleware.cs:line FIXED\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\u0026 stateMachine)\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware\u00601.Execute(SignalMiddlewareContext\u00601 ctx)\n   at Conqueror.Signalling.SignalPipelineRunner\u00601.\u003C\u003Ec__DisplayClass3_2.\u003CExecute\u003Eb__1(TSignal signal, CancellationToken token) in {SolutionDirectory}src/Conqueror/Signalling/SignalPipelineRunner.cs:line FIXED","State":{"Message":"An exception occurred while handling signal on test-transport receiver after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","TransportTypeName":"test-transport","TransportRole":"receiver","ResponseLatency":123.456,"SignalId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling signal on {TransportTypeName:l} {TransportRole:l} after {ResponseLatency:0.0000}ms (Signal ID: {SignalId:l}, Trace ID: {TraceId:l})"}}
{"EventId":712209902,"LogLevel":"Error","Category":"CustomCategory_TestSignalWithCustomTransport","Message":"An exception occurred while handling signal on test-transport publisher after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomTransportHandler.Handle(TestSignalWithCustomTransport signal, CancellationToken cancellationToken) in {ProjectDirectory}Signalling/LoggingMiddlewareTestSignals.cs:line FIXED\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware\u00601.Execute(SignalMiddlewareContext\u00601 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Signalling/LoggingSignalMiddleware.cs:line FIXED\n   at Conqueror.Signalling.SignalPipelineRunner\u00601.Execute(IServiceProvider serviceProvider, TSignal initialSignal, ISignalPublisher\u00601 publisher, SignalTransportType transportType, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SignalPipelineRunner.cs:line FIXED\n   at Conqueror.Signalling.SignalDispatcher\u00601.Dispatch(TSignal signal, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SignalDispatcher.cs:line FIXED\n   at Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalPublisher\u00601.Publish(TSignal signal, IServiceProvider serviceProvider, ConquerorContext conquerorContext, CancellationToken cancellationToken) in {ProjectDirectory}Signalling/LoggingMiddlewareTestSignals.cs:line FIXED","State":{"Message":"An exception occurred while handling signal on test-transport publisher after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","TransportTypeName":"test-transport","TransportRole":"publisher","ResponseLatency":123.456,"SignalId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling signal on {TransportTypeName:l} {TransportRole:l} after {ResponseLatency:0.0000}ms (Signal ID: {SignalId:l}, Trace ID: {TraceId:l})"}}
