{"EventId":711195907,"LogLevel":"Information","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithCustomSerializedPayloadType","Message":"Handling message with payload TestMessageWithCustomSerializedPayloadType { Payload = TestMessageWithCustomSerializedPayloadTypePayload { Payload = 10 } } (Message ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling message with payload TestMessageWithCustomSerializedPayloadType { Payload = TestMessageWithCustomSerializedPayloadTypePayload { Payload = 10 } } (Message ID: test-message-id, Trace ID: test-trace-id)","MessagePayload":"TestMessageWithCustomSerializedPayloadType { Payload = TestMessageWithCustomSerializedPayloadTypePayload { Payload = 10 } }","MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling message with payload {@MessagePayload:l} (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":2027292319,"LogLevel":"Error","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithCustomSerializedPayloadType","Message":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithCustomSerializedPayloadTypeHandler.Handle(TestMessageWithCustomSerializedPayloadType message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line 804\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line 52\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\u0026 stateMachine)\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx)\n   at Conqueror.Messaging.MessagePipelineRunner\u00602.\u003C\u003Ec__DisplayClass3_2.\u003CExecute\u003Eb__1(TMessage message, CancellationToken token) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line 36","State":{"Message":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling message after {ResponseLatency:0.0000}ms (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
