{"EventId":711195907,"LogLevel":"Information","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse","Message":"Sending in-process message of type \u0027TestMessageWithoutResponse\u0027 with payload {\u0022Payload\u0022:10} (Message ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Sending in-process message of type \u0027TestMessageWithoutResponse\u0027 with payload {\u0022Payload\u0022:10} (Message ID: test-message-id, Trace ID: test-trace-id)","MessageTypeName":"TestMessageWithoutResponse","MessagePayload":"{\u0022Payload\u0022:10}","MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Sending in-process message of type \u0027{MessageTypeName}\u0027 with payload {@MessagePayload:l} (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":711195907,"LogLevel":"Information","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseHandler","Message":"Handling message of type \u0027TestMessageWithoutResponse\u0027 with payload {\u0022Payload\u0022:10} (Message ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling message of type \u0027TestMessageWithoutResponse\u0027 with payload {\u0022Payload\u0022:10} (Message ID: test-message-id, Trace ID: test-trace-id)","MessageTypeName":"TestMessageWithoutResponse","MessagePayload":"{\u0022Payload\u0022:10}","MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling message of type \u0027{MessageTypeName}\u0027 with payload {@MessagePayload:l} (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":2027292319,"LogLevel":"Error","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseHandler","Message":"An exception occurred while handling message of type \u0027TestMessageWithoutResponse\u0027 after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseHandler.Handle(TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler.global::Conqueror.IMessageHandler\u003CConqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse,Conqueror.UnitMessageResponse,Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler\u003E.Invoke(IHandler handler, TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}obj/Debug/net8.0/Conqueror.SourceGenerators/Conqueror.SourceGenerators.Messaging.MessageTypeGenerator/Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse_ConquerorMessageType.g.cs:line FIXED\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED\n   at Conqueror.Messaging.MessagePipelineRunner\u00602.\u003C\u003Ec__DisplayClass3_2.\u003CExecute\u003Eb__1(TMessage message, CancellationToken token) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line FIXED\n   at Conqueror.Messaging.MessagePipelineRunner\u00602.Execute(IServiceProvider serviceProvider, TMessage initialMessage, IMessageSender\u00602 sender, MessageTransportType transportType, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line FIXED","State":{"Message":"An exception occurred while handling message of type \u0027TestMessageWithoutResponse\u0027 after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","MessageTypeName":"TestMessageWithoutResponse","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling message of type \u0027{MessageTypeName}\u0027 after {ResponseLatency:0.0000}ms (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":2027292319,"LogLevel":"Error","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse","Message":"An exception occurred while sending in-process message of type \u0027TestMessageWithoutResponse\u0027 after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseHandler.Handle(TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler.global::Conqueror.IMessageHandler\u003CConqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse,Conqueror.UnitMessageResponse,Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler\u003E.Invoke(IHandler handler, TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}obj/Debug/net8.0/Conqueror.SourceGenerators/Conqueror.SourceGenerators.Messaging.MessageTypeGenerator/Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse_ConquerorMessageType.g.cs:line FIXED\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED\n   at Conqueror.Messaging.MessagePipelineRunner\u00602.Execute(IServiceProvider serviceProvider, TMessage initialMessage, IMessageSender\u00602 sender, MessageTransportType transportType, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line FIXED\n   at Conqueror.Messaging.MessageDispatcher\u00602.Dispatch(TMessage message, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/MessageDispatcher.cs:line FIXED","State":{"Message":"An exception occurred while sending in-process message of type \u0027TestMessageWithoutResponse\u0027 after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","MessageTypeName":"TestMessageWithoutResponse","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while sending in-process message of type \u0027{MessageTypeName}\u0027 after {ResponseLatency:0.0000}ms (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
