info: CustomCategory_TestMessageWithoutResponseWithoutPayload[711195907]
      Handling message (Message ID: test-message-id, Trace ID: test-trace-id)
fail: CustomCategory_TestMessageWithoutResponseWithoutPayload[2027292319]
      An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)
      Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages+TestException: test exception
         at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayloadHandler.Handle(TestMessageWithoutResponseWithoutPayload message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line 738
         at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayload.IHandler.global::Conqueror.IMessageHandler<Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayload,Conqueror.UnitMessageResponse,Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayload.IHandler>.Invoke(IHandler handler, TestMessageWithoutResponseWithoutPayload message, CancellationToken cancellationToken) in {ProjectDirectory}obj\Debug\net8.0\Conqueror.SourceGenerators\Conqueror.SourceGenerators.Messaging.MessageTypeGenerator\Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayload_ConquerorMessageType.g.cs:line 38
         at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line 52
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx)

