{"EventId":711195907,"LogLevel":"Information","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse","Message":"Handling message with payload\n{\n  \u0022Payload\u0022: 10\n}\n(Message ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling message with payload\n{\n  \u0022Payload\u0022: 10\n}\n(Message ID: test-message-id, Trace ID: test-trace-id)","MessagePayload":"{\n  \u0022Payload\u0022: 10\n}","MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling message with payload\n{@MessagePayload:l}\n(Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":2027292319,"LogLevel":"Error","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse","Message":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseHandler.Handle(TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line 719\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler.global::Conqueror.IMessageHandler\u003CConqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse,Conqueror.UnitMessageResponse,Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler\u003E.Invoke(IHandler handler, TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}obj\Debug\net8.0\Conqueror.SourceGenerators\Conqueror.SourceGenerators.Messaging.MessageTypeGenerator\Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse_ConquerorMessageType.g.cs:line 38\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line 52\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\u0026 stateMachine)\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx)","State":{"Message":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling message after {ResponseLatency:0.0000}ms (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
