{"@t":"2020-01-01T00:00:00.0000000Z","@m":"Handling message with payload TestMessageSub { PayloadBase = 10, PayloadSub = 11 } (Message ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","MessagePayload":"TestMessageSub { PayloadBase = 10, PayloadSub = 11 }","MessageId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":711195907,"Name":"conqueror-message"},"SourceContext":"CustomCategory_TestMessageSub"}
{"@t":"2020-01-01T00:00:00.0000000Z","@m":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","@l":"Error","@x":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages+TestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageBaseHandler.Handle(TestMessageBase message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line 923\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line 52\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx)\n   at Conqueror.Messaging.MessagePipelineRunner`2.<>c__DisplayClass3_2.<Execute>b__1(TMessage message, CancellationToken token) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line 36","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":2027292319,"Name":"conqueror-message-exception"},"SourceContext":"CustomCategory_TestMessageSub"}
