2020-01-01 00:00:00.000 +00:00 [Information] Handling message on in-process sender with payload {"Payload":10} (Message ID: test-message-id, Trace ID: test-trace-id)
2020-01-01 00:00:00.000 +00:00 [Information] Handling message with payload {"Payload":10} (Message ID: test-message-id, Trace ID: test-trace-id)
2020-01-01 00:00:00.000 +00:00 [Error] An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)
Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages+TestException: test exception
   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseHandler.Handle(TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED
   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler.global::Conqueror.IMessageHandler<Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse,Conqueror.UnitMessageResponse,Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler>.Invoke(IHandler handler, TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}obj/Debug/net8.0/Conqueror.SourceGenerators/Conqueror.SourceGenerators.Messaging.MessageTypeGenerator/Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse_ConquerorMessageType.g.cs:line FIXED
   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx)

2020-01-01 00:00:00.000 +00:00 [Error] An exception occurred while handling message on in-process sender after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)
Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages+TestException: test exception
   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseHandler.Handle(TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED
   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler.global::Conqueror.IMessageHandler<Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse,Conqueror.UnitMessageResponse,Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler>.Invoke(IHandler handler, TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}obj/Debug/net8.0/Conqueror.SourceGenerators/Conqueror.SourceGenerators.Messaging.MessageTypeGenerator/Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse_ConquerorMessageType.g.cs:line FIXED
   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED
   at Conqueror.Messaging.MessagePipelineRunner`2.Execute(IServiceProvider serviceProvider, TMessage initialMessage, IMessageSender`2 sender, MessageTransportType transportType, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line FIXED
   at Conqueror.Messaging.MessageDispatcher`2.Dispatch(TMessage message, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/MessageDispatcher.cs:line FIXED

