{"@t":"2020-01-01T00:00:00.0000000Z","@m":"Handling message (Message ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","MessageId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":711195907,"Name":"conqueror-message"},"SourceContext":"CustomCategory_TestMessageSub"}
{"@t":"2020-01-01T00:00:00.0000000Z","@m":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","@l":"Error","@x":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages+TestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageBaseHandler.Handle(TestMessageBase message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line 918\n   at Conqueror.Messaging.InProcessMessageTransport`2.HandlerInvoker.Send(TMessage message, IServiceProvider serviceProvider, ConquerorContext conquerorContext, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/InProcessMessageTransport.cs:line 40\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line 52\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx)","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":2027292319,"Name":"conqueror-message-exception"},"SourceContext":"CustomCategory_TestMessageSub"}
